POST http://localhost:3000/estados
Content-Type: application/json

{
    "nome": "Minas Gerais",
    "sigla": "MG"
}

### 

POST http://localhost:3000/estados
Content-Type: application/json

{
    "nome": "São Paulo",
    "sigla": "SP"
}

###

POST http://localhost:3000/cidades
Content-Type: application/json

{
    "nome": "Belo Horizonte",
    "estado_id": 1
}

###

POST http://localhost:3000/cidades
Content-Type: application/json

{
    "nome": "São Paulo",
    "estado_id": 3
}

###

GET http://localhost:3000/estados

###

GET http://localhost:3000/estados/1

###

GET http://localhost:3000/cidades

###

GET http://localhost:3000/cidades/1

###

PUT http://localhost:3000/estados
Content-Type: application/json

{
    "id": 2,
    "nome": "Rio de Janeiro",
    "sigla": "RJ"
}

###

PUT http://localhost:3000/cidades
Content-Type: application/json

{
    "id": 4, 
    "nome": "Petrópolis",
    "estado_id": 2
}

###

DELETE http://localhost:3000/cidades
Content-Type: application/json

{
    "id": 55
}

### 
DELETE http://localhost:3000/estados
Content-Type: application/json

{
    "id": 32
}

### 
GET http://localhost:4000/users/login

###
POST http://localhost:4000/users/validate
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsb2dpblRpbWUiOiJUdWUgT2N0IDA0IDIwMjIgMTU6MTk6MDcgR01ULTAzMDAgKEJyYXNpbGlhIFN0YW5kYXJkIFRpbWUpIiwidXNlcl9pZCI6MTAsImlhdCI6MTY2NDkwNzU0N30.TUQU0YSXkaJ3QxpLQcXEJYkKuOo2O2_gx1PecqqZK10

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsb2dpblRpbWUiOiJUdWUgT2N0IDA0IDIwMjIgMTU6MTk6MDcgR01ULTAzMDAgKEJyYXNpbGlhIFN0YW5kYXJkIFRpbWUpIiwidXNlcl9pZCI6MTAsImlhdCI6MTY2NDkwNzU0N30.TUQU0YSXkaJ3QxpLQcXEJYkKuOo2O2_gx1PecqqZK10",
  "header": "app_token"
}